IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Employees'))
CREATE TABLE Employees(
	Id INT IDENTITY NOT NULL PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL,
	Position NVARCHAR(50) NOT NULL,
	Status INT NOT NULL,
	Salary MONEY NOT NULL)
